python ./rraa_rl/EFPPO/src/rl/CPPO_RAA.py \
--EXP_NAME=PointReachAlwaysAvoid_CPPO \
--DIR=BASELINE_point_raa_logbar_scale \
--LR=3e-4 \
--NUM_ENVS=128 \
--NUM_STEPS=400 \
--TOTAL_TIMESTEPS=50_000_000 \
--STEP_SCAN=4 \
--UPDATE_EPOCHS=10 \
--NUM_MINIBATCHES=32 \
--GAMMA_ENERGY=1.0 \
--GAMMA_REACH_INIT=0.995 \
--GAMMA_REACH_FINAL=0.9995 \
--GAE_LAMBDA=0.95 \
--LAMBDA_REACH=1.0 \
--LOG_BARRIER_MU=100. \
--LOG_BARRIER \
--FIX_LAMBDA \
--K_P=1.0 \
--THRESHOLD_CPPO=0. \
--CLIP_EPS=0.2 \
--ENT_COEF=0.005 \
--VF_COEF=2.0 \
--MAX_GRAD_NORM=0.5 \
--ACTIVATION=tanh \
--CUDA_USE=0 \
--ANNEAL_LR \
--ANNEAL_ENT \
--NAME=BASELINE_point_raa_logbar_scale

# python ./rraa_rl/EFPPO/src/rl/CPPO_RR.py \
# --EXP_NAME=PointReachReach_CPPO \
# --DIR=BASELINE_point_rr_logbar \
# --LR=3e-4 \
# --NUM_ENVS=128 \
# --NUM_STEPS=400 \
# --TOTAL_TIMESTEPS=100_000_000 \
# --STEP_SCAN=4 \
# --UPDATE_EPOCHS=10 \
# --NUM_MINIBATCHES=32 \
# --GAMMA_ENERGY=1.0 \
# --GAMMA_REACH_INIT=0.995 \
# --GAMMA_REACH_FINAL=0.9995 \
# --GAE_LAMBDA=0.95 \
# --LAMBDA_REACH=1.0 \
# --LOG_BARRIER_MU=1.0 \
# --LOG_BARRIER \
# --FIX_LAMBDA \
# --K_P=1.0 \
# --THRESHOLD_CPPO=0. \
# --CLIP_EPS=0.2 \
# --ENT_COEF=0.005 \
# --VF_COEF=2.0 \
# --MAX_GRAD_NORM=0.5 \
# --ACTIVATION=tanh \
# --CUDA_USE=0 \
# --ANNEAL_LR \
# --ANNEAL_ENT \
# --NAME=BASELINE_point_rr_logbar