python ./rraa_rl/EFPPO/src/rl/MORL_PPO_RR.py \
--EXP_NAME=HalfCheetahReachReachBaseline_Sparse \
--DIR=final_halfcheetah_rr_sparse \
--LR=3e-4 \
--NUM_ENVS=128 \
--NUM_STEPS=400 \
--TOTAL_TIMESTEPS=150_000_000 \
--STEP_SCAN=4 \
--UPDATE_EPOCHS=10 \
--NUM_MINIBATCHES=32 \
--GAMMA_ENERGY=1.0 \
--GAMMA_REACH_INIT=0.995 \
--GAMMA_REACH_FINAL=0.9995 \
--GAE_LAMBDA=0.95 \
--LAMBDA_REACH=0.0 \
--FIX_LAMBDA \
--K_P=10.0 \
--THRESHOLD_CPPO=0. \
--CLIP_EPS=0.2 \
--ENT_COEF=0.005 \
--VF_COEF=2.0 \
--MAX_GRAD_NORM=0.5 \
--ACTIVATION=tanh \
--CUDA_USE=1 \
--ANNEAL_LR \
--ANNEAL_ENT \
--NAME=final_halfcheetah_rr_sparse