python ./rraa_rl/src/rl/RR-PPO.py \
--EXP_NAME=HalfCheetahReachReach \
--DIR=halfcheetah_rr_resetgoal_reachv0.1_rerun \
--LR=3e-4 \
--NUM_ENVS=128 \
--NUM_STEPS=400 \
--TOTAL_TIMESTEPS=150_000_000 \
--STEP_SCAN=4 \
--UPDATE_EPOCHS=10 \
--NUM_MINIBATCHES=32 \
--GAMMA_ENERGY=1.0 \
--GAMMA_REACH_INIT=0.995 \
--GAMMA_REACH_FINAL=0.9995 \
--GAE_LAMBDA=0.95 \
--CLIP_EPS=0.2 \
--ENT_COEF=0.005 \
--VF_COEF=2.0 \
--MAX_GRAD_NORM=0.5 \
--ACTIVATION=tanh \
--CUDA_USE=0 \
--ANNEAL_LR \
--ANNEAL_ENT \
--NAME=halfcheetah_rr_resetgoal_reachv0.1_rerun